from typing import Protocol
import numpy as np

class KoopmanModel(Protocol):
    def lift(self, x: np.ndarray) -> np.ndarray: ...
    def predict(self, z: np.ndarray, u: np.ndarray) -> np.ndarray: ...
    def decode(self, z: np.ndarray) -> np.ndarray: ...
    @property
    def A(self) -> np.ndarray: ...
    @property
    def B(self) -> np.ndarray: ...
    @property
    def C(self) -> np.ndarray: ...

class MPCKoopman(Protocol):
    def set_koopman(self, model: KoopmanModel) -> None: ...
