from typing import Protocol, Optional, Dict, Any, Tuple
import numpy as np

class StageCost(Protocol):
    def l(self, x: np.ndarray, u: np.ndarray, r: Optional[Dict[str, np.ndarray]] = None) -> float: ...
    def grads(self, x: np.ndarray, u: np.ndarray, r: Optional[Dict[str, np.ndarray]] = None) -> Tuple[np.ndarray, np.ndarray]: ...

class TerminalCost(Protocol):
    def m(self, x: np.ndarray, r: Optional[Dict[str, np.ndarray]] = None) -> float: ...
    def grad(self, x: np.ndarray, r: Optional[Dict[str, np.ndarray]] = None) -> np.ndarray: ...
