from typing import Protocol
import numpy as np

class QuaternionOps(Protocol):
    """Hamilton convention, scalar-first."""
    def normalize(self, q: np.ndarray) -> np.ndarray: ...
    def compose(self, q2: np.ndarray, q1: np.ndarray) -> np.ndarray: ...
    def rotate(self, q: np.ndarray, v: np.ndarray) -> np.ndarray: ...
    def to_dcm(self, q: np.ndarray) -> np.ndarray: ...
