from typing import Protocol
import numpy as np

class Scaler(Protocol):
    def fit(self, X: np.ndarray) -> None: ...
    def transform(self, x: np.ndarray) -> np.ndarray: ...
    def inverse_transform(self, x: np.ndarray) -> np.ndarray: ...
