from typing import Protocol
import numpy as np

class CBF(Protocol):
    name: str
    def h(self, x: np.ndarray) -> float: ...
    def grad(self, x: np.ndarray) -> np.ndarray: ...
    def alpha(self, h_val: float) -> float: ...
